#!/usr/bin/env bash
set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

BASENAME=$(basename "$FILE_PATH")

case "$BASENAME" in
  .env.example) ;;
  .env|.env.*)
    echo "Blocked: $FILE_PATH is an env file. Only .env.example is safe to edit." >&2
    exit 2
    ;;
esac

# Substring-matched anywhere in the path.
PROTECTED_PATHS=( ".git/" "package-lock.json" )
for p in "${PROTECTED_PATHS[@]}"; do
  if [[ "$FILE_PATH" == *"$p"* ]]; then
    echo "Blocked: $FILE_PATH matches protected pattern '$p'. Propose the change in chat instead." >&2
    exit 2
  fi
done

# Native project dirs are protected only at the REPO ROOT ($CLAUDE_PROJECT_DIR/ios,
# $CLAUDE_PROJECT_DIR/android) — the expo-prebuild output. Paths like
# fastlane/metadata/android/<locale>/ are intentional Play-listing content and
# must stay editable, so don't match a bare "android/" anywhere in the tree.
ROOT="${CLAUDE_PROJECT_DIR:-}"
if [[ -n "$ROOT" ]]; then
  for d in ios android; do
    if [[ "$FILE_PATH" == "$ROOT/$d/"* ]]; then
      echo "Blocked: $FILE_PATH is in the generated native '$d/' project (regenerated by EAS/prebuild). Propose the change in chat instead." >&2
      exit 2
    fi
  done
fi

exit 0
